# Generated by Django 4.2.3 on 2023-07-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comments_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='currentBid',
            field=models.IntegerField(default=0),
        ),
    ]
