# Generated by Django 4.2.3 on 2023-07-25 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_watchlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.auctionlisting')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_user', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
